name: Build pipeline

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up docker-compose
      uses: parisk/setup-compose-cli@v1
    
    - name: Run docker-compose
      run: docker-compose -f ./build/docker-compose.yml -f ./build/docker-compose.CI.yml up --build --abort-on-container-exit --force-recreate
    
    - name: Publish test results
      id: publishTestResults
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Test results      
        path: 'test-results/**/*.trx'    
        reporter: dotnet-trx  
        fail-on-error: 'true'
    
    - name: Test coverage
      if: success() || failure()
      uses: 5monkeys/cobertura-action@master
      with:
        path: 'test-results/**/*.cobertura.xml'
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        minimum_coverage: 0
        
    - name: Create test result badge successful tests
      if: success() || failure()
      uses: schneegans/dynamic-badges-action@v1.4.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: ${{ secrets.TEST_RESULTS_GIST_ID }}
        filename: testresult_success.json
        label: Tests passed
        message: ${{ steps.publishTestResults.outputs.passed }}
        color: green
        
    - name: Create test result badge failed tests
      if: success() || failure()
      uses: schneegans/dynamic-badges-action@v1.4.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: ${{ secrets.TEST_RESULTS_GIST_ID }}
        filename: testresult_failed.json
        label: Tests failed
        message: ${{ steps.publishTestResults.outputs.failed }}
        color: red
        
