name: Deploy to PROD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: SFTP Deploy
      uses: wlixcc/SFTP-Deploy-Action@v1.2.2
      with:
        username: ${{ secrets.PROD_SFTP_USER }}
        server: ${{ secrets.PROD_IP }}
        port: ${{ secrets.PROD_SFTP_PORT }}
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        remote_path: ${{ secrets.PROD_SFTP_PATH }}
