name: Deploy to PROD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: SFTP Deploy
      uses: wlixcc/SFTP-Deploy-Action@v1.2.2
      with:
        username: ${{ secrets.PROD_SFTP_USER }}
        server: ${{ secrets.PROD_IP }}
        port: ${{ secrets.PROD_SFTP_PORT }}
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        remote_path: ${{ secrets.PROD_SFTP_PATH }}
        
    - name: Move Files
    # You may pin to the exact commit or the version.
    # uses: fifsky/ssh-action@58b3c484be9c20cf118fd3b939a6d2cb3c769512
      uses: fifsky/ssh-action@v0.0.6
      with:
        # Command to execute on the remote server.
        command: cp -r ${{ secrets.PROD_SFTP_PATH }}/* ${{ secrets.PROD_APPLICATION_PATH }}/
        # Hostname or IP address of the server.
        host: ${{ secrets.PROD_IP }}
        # Username for authentication.
        user: ${{ secrets.PROD_APPLICATION_USERNAME }}
        # Port number of the server.
        port: ${{ secrets.PROD_SFTP_PORT }}
        # String that contains a private key for either key-based or hostbased user authentication (OpenSSH format)
        key: ${{ secrets.PROD_APPLICATION_USER_SSH_PRIVATE_KEY }}
        
    - name: Build and start via docker
    # You may pin to the exact commit or the version.
    # uses: fifsky/ssh-action@58b3c484be9c20cf118fd3b939a6d2cb3c769512
      uses: fifsky/ssh-action@v0.0.6
      with:
        # Command to execute on the remote server.
        command: cd ${{ secrets.PROD_APPLICATION_PATH }} && docker-compose -f ./build/docker-compose.yml up --build --force-recreate -d
        # Hostname or IP address of the server.
        host: ${{ secrets.PROD_IP }}
        # Username for authentication.
        user: ${{ secrets.PROD_APPLICATION_USERNAME }}
        # Port number of the server.
        port: ${{ secrets.PROD_SFTP_PORT }}
        # String that contains a private key for either key-based or hostbased user authentication (OpenSSH format)
        key: ${{ secrets.PROD_APPLICATION_USER_SSH_PRIVATE_KEY }}
        
        
        
        
