name: Deploy to Heroku DEV

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    # Copy Dockerfile from build as there is no possibility to configure the build call for heroku (it needs to be called from the parent directory
    - name: Move Dockerfile
      run: mv ./build/Dockerfile .
    
    - name: Login Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME_DEV }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        justlogin: true
       
    - name: Login to Heroku registry
      run: heroku container:login
     
    # This command implicitly build the Dockerfile as well. This is also why we needed to copy it to the project root. Sadly specifying a specific target is not supported 
    # see (https://github.com/AkhileshNS/heroku-deploy/issues/66) therefore the build takes longer to run as all stages are executed. In the future a specific Dockerfile for Heroku could be provided.
    - name: Push container
      run: heroku container:push web --app ${{ secrets.HEROKU_APP_NAME_DEV }}
      
    - name: Release container
      run: heroku container:release web --app ${{ secrets.HEROKU_APP_NAME_DEV }}
